# Generated by Django 4.2.1 on 2023-05-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='text',
            field=models.TextField(default=''),
        ),
    ]