# Generated by Django 4.2.1 on 2023-05-22 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_profile_alter_answers_user_alter_questions_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default_avatar.jpg', upload_to='avatars/%Y/%m/%d/'),
        ),
    ]
