# Generated by Django 4.2.1 on 2023-06-16 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0008_remove_questions_likes_profile_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='likes',
            new_name='question_likes',
        ),
        migrations.AddField(
            model_name='profile',
            name='answer_likes',
            field=models.ManyToManyField(to='askme.answers'),
        ),
    ]
