# Generated by Django 4.2.1 on 2023-06-16 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0009_rename_likes_profile_question_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='answer_likes',
        ),
    ]
