# Generated by Django 4.2.1 on 2023-06-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0014_remove_profile_answer_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlike',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='askme.profile'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='askme.profile'),
        ),
    ]
