# Generated by Django 4.2.1 on 2023-06-19 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0016_remove_questionlike_object_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestionLike',
        ),
    ]
