# Generated by Django 4.2.1 on 2023-06-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0021_remove_questions_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
