# Generated by Django 4.2.1 on 2023-06-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0022_answers_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
