# Generated by Django 4.2.1 on 2023-06-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0023_questions_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='rating',
        ),
    ]
